name: Chrome Stable

on: [workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Build the chrome-stable image
      run: docker build --build-arg "USE_CHROME_STABLE=true" -t ghcr.io/volition-co/chrome:stable .

    - name: Test the chrome-stable image
      run: docker run --ipc=host -e CI=true --entrypoint ./test.sh ghcr.io/volition-co/chrome:stable
